{{- if .Values.serviceAccount.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cloudquery
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "cloudquery_rds"
          objectType: "secretsmanager"
{{- end }}